[package]
name = "expression_simplify"
version = "1.0.0"
edition = "2021"
author = "sudo-dqr"
description = "A simple expression simplifier based on OO course(SCSE, BUAA)"
license = "MIT"

[dependencies]
